2021-09-23 15:27:03,220 INFO    MainThread:16158 [internal.py:wandb_internal():89] W&B internal server running at pid: 16158, started at: 2021-09-23 15:27:03.219380
2021-09-23 15:27:03,232 INFO    WriterThread:16158 [datastore.py:open_for_write():77] open: output/wandb/offline-run-20210923_152701-fpk8llmr/run-fpk8llmr.wandb
2021-09-23 15:27:03,233 DEBUG   HandlerThread:16158 [handler.py:handle_request():126] handle_request: run_start
2021-09-23 15:27:08,925 DEBUG   HandlerThread:16158 [meta.py:__init__():40] meta init
2021-09-23 15:27:08,926 DEBUG   HandlerThread:16158 [meta.py:__init__():54] meta init done
2021-09-23 15:27:08,926 DEBUG   HandlerThread:16158 [meta.py:probe():211] probe
2021-09-23 15:27:08,960 DEBUG   HandlerThread:16158 [meta.py:_setup_git():201] setup git
2021-09-23 15:27:09,022 DEBUG   HandlerThread:16158 [meta.py:_setup_git():208] setup git done
2021-09-23 15:27:09,022 DEBUG   HandlerThread:16158 [meta.py:_save_pip():58] save pip
2021-09-23 15:27:09,023 DEBUG   HandlerThread:16158 [meta.py:_save_pip():72] save pip done
2021-09-23 15:27:09,027 DEBUG   HandlerThread:16158 [meta.py:_save_conda():79] save conda
2021-09-23 15:27:19,082 DEBUG   HandlerThread:16158 [meta.py:_save_conda():87] save conda done
2021-09-23 15:27:19,096 DEBUG   HandlerThread:16158 [meta.py:probe():249] probe done
2021-09-23 15:27:30,435 WARNING MainThread:16158 [internal.py:wandb_internal():145] Internal process interrupt: 1
2021-09-23 15:27:30,511 WARNING MainThread:16158 [internal.py:wandb_internal():145] Internal process interrupt: 2
2021-09-23 15:27:30,511 ERROR   MainThread:16158 [internal.py:wandb_internal():148] Internal process interrupted.
2021-09-23 15:27:31,168 INFO    WriterThread:16158 [datastore.py:close():281] close: output/wandb/offline-run-20210923_152701-fpk8llmr/run-fpk8llmr.wandb
2021-09-23 15:27:31,410 INFO    SenderThread:16158 [sender.py:finish():979] shutting down sender
2021-09-23 15:27:31,414 INFO    MainThread:16158 [internal.py:handle_exit():76] Internal process exited
