2021-10-11 19:05:28,000 INFO    MainThread:26323 [internal.py:wandb_internal():91] W&B internal server running at pid: 26323, started at: 2021-10-11 19:05:28.000088
2021-10-11 19:05:28,003 DEBUG   HandlerThread:26323 [handler.py:handle_request():124] handle_request: run_start
2021-10-11 19:05:28,003 INFO    WriterThread:26323 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20211011_190527-3nnbs3zr/run-3nnbs3zr.wandb
2021-10-11 19:05:28,872 DEBUG   HandlerThread:26323 [meta.py:__init__():39] meta init
2021-10-11 19:05:28,872 DEBUG   HandlerThread:26323 [meta.py:__init__():53] meta init done
2021-10-11 19:05:28,872 DEBUG   HandlerThread:26323 [meta.py:probe():210] probe
2021-10-11 19:05:28,879 DEBUG   HandlerThread:26323 [meta.py:_setup_git():200] setup git
2021-10-11 19:05:28,902 DEBUG   HandlerThread:26323 [meta.py:_setup_git():207] setup git done
2021-10-11 19:05:28,902 DEBUG   HandlerThread:26323 [meta.py:_save_pip():57] save pip
2021-10-11 19:05:28,903 DEBUG   HandlerThread:26323 [meta.py:_save_pip():71] save pip done
2021-10-11 19:05:28,903 DEBUG   HandlerThread:26323 [meta.py:_save_conda():78] save conda
2021-10-11 19:05:31,704 DEBUG   HandlerThread:26323 [meta.py:_save_conda():86] save conda done
2021-10-11 19:05:31,704 DEBUG   HandlerThread:26323 [meta.py:probe():252] probe done
2021-10-11 19:05:39,404 WARNING MainThread:26323 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-10-11 19:05:39,537 WARNING MainThread:26323 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-10-11 19:05:39,538 ERROR   MainThread:26323 [internal.py:wandb_internal():150] Internal process interrupted.
2021-10-11 19:05:39,742 INFO    WriterThread:26323 [datastore.py:close():288] close: output/wandb/offline-run-20211011_190527-3nnbs3zr/run-3nnbs3zr.wandb
2021-10-11 19:05:40,010 INFO    SenderThread:26323 [sender.py:finish():947] shutting down sender
2021-10-11 19:05:40,010 INFO    MainThread:26323 [internal.py:handle_exit():78] Internal process exited
